packages:
  pkg.installed:
    - pkgs:
      - acpi
      - alsa-utils
      - ansible
      - aspell-en
      - automake
      - bash-completion
      - bind-tools
      - binutils
      - bison
      - bitlbee
      - bridge-utils
      - chromium
      - cups
      - cups-pdf
      - curl
      - dialog
      - dmenu
      - dmidecode
      - dnsmasq
      - dosfstools
      - dropbox
      - dstat
      - dunst
      - ebtables
      - efibootmgr
      - eog
      - ethtool
      - evince
      - exfat-utils
      - exo
      - fakeroot
      - figlet
      - firefox
      - flex
      - garcon
      - gc
      - gcc
      - ghostscript
      - gimp
      - git
      - go
      - gsfonts
      - gtk-xfce-engine
      - guile
      - htop
      - i3-wm
      - i3lock
      - i3status
      - imagemagick
      - intel-ucode
      - iotop
      - ipcalc
      - ipython
      - iw
      - jq
      - lib32-mesa-libgl
      - libmpc
      - libva-intel-driver
      - libvirt
      - lm_sensors
      - lsscsi
      - make
      - mercurial
      - mousepad
      - mplayer
      - mpv
      - mtr
      - neovim
      - networkmanager
      - networkmanager-openvpn
      - nftables
      - nload
      - nmap
      - notify-osd
      - ntfs-3g
      - openbsd-netcat
      - openssh
      - openvpn
      - orage
      - p7zip
      - parted
      - pavucontrol
      - pkg-config
      - pkgfile
      - powertop
      - pulseaudio
      - qemu
      - redshift
      - ristretto
      - rsync
      - rxvt-unicode
      - scrot
      - strace
      - sudo
      - sysstat
      - system-config-printer
      - tcpdump
      - thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-volman
      - tlp
      - tmux
      - transmission-gtk
      - ttf-bitstream-vera
      - tumbler
      - unzip
      - vim
      - virt-manager
      - weechat
      - wget
      - whois
      - wpa_supplicant
      - x11-ssh-askpass 
      - xautolock
      - xf86-input-libinput
      - xf86-video-intel
      - xfburn
      - xfce4-appfinder
      - xfce4-artwork
      - xfce4-battery-plugin
      - xfce4-clipman-plugin
      - xfce4-cpufreq-plugin
      - xfce4-cpugraph-plugin
      - xfce4-datetime-plugin
      - xfce4-dict
      - xfce4-diskperf-plugin
      - xfce4-eyes-plugin
      - xfce4-fsguard-plugin
      - xfce4-genmon-plugin
      - xfce4-mailwatch-plugin
      - xfce4-mixer
      - xfce4-mount-plugin
      - xfce4-mpc-plugin
      - xfce4-netload-plugin
      - xfce4-notes-plugin
      - xfce4-notifyd
      - xfce4-panel
      - xfce4-power-manager
      - xfce4-screenshooter
      - xfce4-sensors-plugin
      - xfce4-session
      - xfce4-settings
      - xfce4-smartbookmark-plugin
      - xfce4-systemload-plugin
      - xfce4-taskmanager
      - xfce4-terminal
      - xfce4-time-out-plugin
      - xfce4-timer-plugin
      - xfce4-verve-plugin
      - xfce4-wavelan-plugin
      - xfce4-weather-plugin
      - xfce4-whiskermenu-plugin
      - xfce4-xkb-plugin
      - xfconf
      - xfdesktop
      - xfwm4
      - xfwm4-themes
      - xorg-bdftopcf
      - xorg-luit
      - xorg-mkfontdir
      - xorg-mkfontscale
      - xorg-server
      - xorg-server-utils
      - xorg-setxkbmap
      - xorg-smproxy
      - xorg-x11perf
      - xorg-xauth
      - xorg-xcursorgen
      - xorg-xdpyinfo
      - xorg-xdriinfo
      - xorg-xev
      - xorg-xinit
      - xorg-xkbcomp
      - xorg-xkbevd
      - xorg-xkbutils
      - xorg-xkill
      - xorg-xlsatoms
      - xorg-xlsclients
      - xorg-xpr
      - xorg-xprop
      - xorg-xvinfo
      - xorg-xwd
      - xorg-xwininfo
      - xorg-xwud
      - xsel
      - yaourt
    - require:
      - file: /etc/pacman.conf

# vim
/home/gms/.vim/autoload/pathogen.vim:
  file.managed:
    - source: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    - source_hash: md5=a36402926ee8e1e0341b3d52bab75b0d
    - user: gms
    - mode: 0640
    - require:
      - user: gms
      - file: /home/gms/.vim/autoload

vim-go:
  git.latest:
    - name: https://github.com/fatih/vim-go.git
    - target: /home/gms/.vim/bundle/vim-go
    - force_reset: True
    - user: gms
    - require:
      - user: gms
      - file: /home/gms/.vim/bundle
      - pkg: packages

vim-colors-solarized:
  git.latest:
    - name: https://github.com/altercation/vim-colors-solarized.git
    - target: /home/gms/.vim/bundle/vim-colors-solarized
    - user: gms
    - require:
      - user: gms
      - file: /home/gms/.vim/bundle
      - pkg: packages

salt-vim:
  git.latest:
    - name: https://github.com/saltstack/salt-vim.git
    - target: /home/gms/.vim/bundle/salt-vim
    - user: gms
    - require:
      - user: gms
      - file: /home/gms/.vim/bundle
      - pkg: packages

bin:
  git.latest:
    - name: https://github.com/lero/shell.git
    - target: /home/gms/bin
    - user: gms
    - require:
      - user: gms
      - pkg: packages

# aur
{% for p in salt['pillar.get']('aur', []) %}
{{ p }}:
  cmd.run:
    - name: su -c "yaourt -S {{ p }} --noconfirm" gms
    - unless: pacman -Q {{ p }}
{% endfor %}
