aur:
  - dropbox-cli
  - i3blocks
  - jre
  - kbdlight
  - mutt-sidebar
  - neofetch
  - playerctl
  - polysh
  - rxvt-unicode-24bit
  - spotify-beta
  - telegram-desktop-bin
  - tcptraceroute
  - terminus-font-ttf
  - ttf-font-awesome
  - ttf-google-fonts-git
